"""Connectivity rules — kubectl reachability.

Unlike most rules these inspect probe *failures*, so `requires_probes`
is empty. The rule-loop's standard "skip when a required probe failed"
gate is therefore a no-op: this rule always runs.
"""
from typing import Any, Dict, List, Tuple

from finding import Finding  # type: ignore
from probes import classify_kubectl_error  # type: ignore
from .base import Rule, ProbeBundle, kubectl_remediation, doc_link_remediation, make_id


# Same list the UI uses for its diag banner — kept in sync via the rule.
_KUBECTL_PROBES = (
    'probe_pods', 'probe_nodes', 'probe_daemonsets', 'probe_replicasets',
    'probe_deployments_all', 'probe_deployments_kubesystem', 'probe_pdbs',
    'probe_events', 'probe_top_pods', 'probe_top_nodes', 'probe_kubectl_version',
)


_CLASS_COPY: Dict[str, Tuple[str, str, List[Dict[str, str]]]] = {
    'dns': (
        'EKS cluster endpoint not resolvable',
        'kubectl cannot resolve the API server hostname. The cluster has likely '
        'been deleted from AWS, or the DSS attachment is stale and points at an '
        'endpoint that no longer exists.',
        [
            {'title': 'Detach this cluster from DSS (Administration > Clusters)',
             'kind': 'gui-step',
             'body': 'In DSS Administration > Clusters, locate this cluster and click Detach. '
                     'The kubeconfig will be removed and the picker will stop offering it.'},
            {'title': 'Confirm the cluster is gone from AWS',
             'kind': 'kubectl',
             'body': 'aws eks list-clusters --region <your-region>'},
        ],
    ),
    'network': (
        'EKS API unreachable from DSS host',
        'kubectl reaches DNS but cannot open a TCP connection to the API server. '
        'Network policy (VPC routing, security-group egress, NAT, or VPN) is blocking '
        'traffic from the DSS host to the EKS endpoint.',
        [
            {'title': 'Check the DSS host can reach the EKS API endpoint',
             'kind': 'kubectl',
             'body': 'aws eks describe-cluster --name <name> --region <region> --query "cluster.endpoint"\n# then from the DSS host:\ncurl -kv https://<that-endpoint>/healthz'},
            {'title': 'Public vs private endpoint access',
             'kind': 'doc-link',
             'body': 'https://docs.aws.amazon.com/eks/latest/userguide/cluster-endpoint.html'},
        ],
    ),
    'auth': (
        'kubectl auth failed',
        'The DSS-side IAM identity is rejected by the cluster. Likely causes: the '
        'assumed role is missing the eks:DescribeCluster / sts:GetCallerIdentity '
        'permission, the role is not mapped in aws-auth ConfigMap, or the cached '
        'STS token has expired.',
        [
            {'title': 'Verify the role-to-username mapping in aws-auth',
             'kind': 'kubectl',
             'body': 'kubectl -n kube-system get configmap aws-auth -o yaml'},
            {'title': 'EKS authentication docs',
             'kind': 'doc-link',
             'body': 'https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html'},
        ],
    ),
    'tls': (
        'TLS handshake failed',
        'kubectl rejects the cluster TLS certificate. Either the cluster CA in the '
        'kubeconfig is stale (regenerated by AWS), or a corporate middlebox is '
        'intercepting the connection and substituting its own cert.',
        [
            {'title': 'Refresh the kubeconfig from AWS',
             'kind': 'kubectl',
             'body': 'aws eks update-kubeconfig --name <cluster> --region <region>'},
        ],
    ),
    'unknown': (
        'kubectl is failing for an unrecognized reason',
        'Every kubectl probe in this audit failed with errors that do not match the '
        'known dns/network/auth/tls patterns. Inspect the probe stderr for clues.',
        [
            {'title': 'Re-run a representative kubectl call manually',
             'kind': 'kubectl',
             'body': 'kubectl get nodes -v=6'},
        ],
    ),
}


class RuleClusterEndpointUnreachable(Rule):
    """When ≥80% of kubectl probes failed with the same error class, emit one
    critical finding. This is the diff between "metrics-server is missing"
    and "the cluster endpoint itself is gone" — the former is one failed
    probe, the latter is all of them with the same DNS / network / TLS error.
    """

    id = 'cluster-endpoint-unreachable'
    category = 'health'
    severity = 'critical'
    requires_probes: List[str] = []

    def evaluate(self, probes: ProbeBundle) -> List[Finding]:
        class_counts: Dict[str, int] = {}
        sampled_stderr: Dict[str, str] = {}
        sampled_probe: Dict[str, str] = {}
        failed = 0
        for name in _KUBECTL_PROBES:
            p = probes.get(name) or {}
            if p.get('ok'):
                continue
            failed += 1
            stderr = (p.get('stderrFull') or p.get('error') or '') or ''
            cls = classify_kubectl_error(stderr)
            class_counts[cls] = class_counts.get(cls, 0) + 1
            sampled_stderr.setdefault(cls, stderr[:600])
            sampled_probe.setdefault(cls, name)

        total = len(_KUBECTL_PROBES)
        if failed == 0:
            return []
        if not class_counts:
            return []

        dominant_class, dominant_count = max(class_counts.items(), key=lambda kv: kv[1])
        if dominant_count / total < 0.80:
            return []

        title, summary, remediations = _CLASS_COPY[dominant_class]
        return [Finding(
            id=make_id(self.id, dominant_class),
            rule=self.id,
            severity=self.severity,
            category=self.category,
            title=title,
            summary=summary,
            evidence={
                'errorClass': dominant_class,
                'failedKubectlProbes': failed,
                'totalKubectlProbes': total,
                'sampleProbe': sampled_probe[dominant_class],
                'sampleStderr': sampled_stderr[dominant_class],
                'classCounts': class_counts,
            },
            remediation=[_remediation_from_dict(r) for r in remediations],
        )]


def _remediation_from_dict(r: Dict[str, str]):
    """Build a Remediation from the literal dicts in _CLASS_COPY."""
    kind = r.get('kind') or 'doc-link'
    title = r.get('title') or ''
    body = r.get('body') or ''
    if kind == 'kubectl':
        return kubectl_remediation(title, body)
    if kind == 'doc-link':
        return doc_link_remediation(title, body)
    from finding import Remediation  # type: ignore
    return Remediation(kind=kind, title=title, body=body)


RULES = [RuleClusterEndpointUnreachable()]
