"""Fixed-argv docker command policy.

Only four operations exist, each compiled to an EXACT argv list — no shell,
no interpolation of free text, no ``system prune``, no ``--all``, no volume
or network pruning. Anything else raises ValueError. daemon.json cache limits
are never executed by the toolkit: :func:`daemon_json_script` emits a tight,
idempotent sudo script for a human admin to run.
"""

OPS = ('df', 'info', 'builder-prune', 'image-prune')


def _int_in_range(value, name, lo, hi):
    try:
        v = int(value)
    except (TypeError, ValueError):
        raise ValueError('%s must be an integer (got %r)' % (name, value))
    if not (lo <= v <= hi):
        raise ValueError('%s must be between %d and %d (got %d)' % (name, lo, hi, v))
    return v


def build_command(op, keep_storage_gb=None, filter_until_hours=None):
    """Compile one whitelisted docker operation to a fixed argv list."""
    if op == 'df':
        return ['docker', 'system', 'df', '--format', '{{json .}}']
    if op == 'info':
        return ['docker', 'info', '--format', '{{json .}}']
    if op == 'builder-prune':
        keep = _int_in_range(keep_storage_gb, 'keep_storage_gb', 1, 10000)
        return ['docker', 'builder', 'prune', '--force', '--keep-storage=%dGB' % keep]
    if op == 'image-prune':
        argv = ['docker', 'image', 'prune', '--force']
        if filter_until_hours not in (None, 0, '0', ''):
            hours = _int_in_range(filter_until_hours, 'filter_until_hours', 1, 24 * 365)
            argv += ['--filter', 'until=%dh' % hours]
        return argv
    raise ValueError('unsupported docker operation %r — allowed: %s' % (op, ', '.join(OPS)))


_DAEMON_SCRIPT_TEMPLATE = '''#!/usr/bin/env bash
# Docker daemon cache limits — generated by Admin Toolkit, run MANUALLY as root.
# Idempotent: merges builder GC + json-file log caps into /etc/docker/daemon.json.
# WARNING: `systemctl restart docker` restarts all running containers.
set -euo pipefail

DAEMON_JSON=/etc/docker/daemon.json
[ -f "$DAEMON_JSON" ] && cp -a "$DAEMON_JSON" "$DAEMON_JSON.bak.$(date +%%Y%%m%%d%%H%%M%%S)"

python3 - "$DAEMON_JSON" <<'PYEOF'
import json, os, sys, tempfile
path = sys.argv[1]
cfg = {}
if os.path.isfile(path):
    with open(path) as fh:
        cfg = json.load(fh) or {}
builder = cfg.setdefault("builder", {}).setdefault("gc", {})
builder["enabled"] = True
builder["defaultKeepStorage"] = "%(keep_gb)dGB"
if cfg.get("log-driver", "json-file") == "json-file":
    opts = cfg.setdefault("log-opts", {})
    opts.setdefault("max-size", "%(log_max_size_mb)dm")
    opts.setdefault("max-file", "%(log_max_file)d")
fd, tmp = tempfile.mkstemp(dir=os.path.dirname(path) or ".", prefix=".daemon.json.")
with os.fdopen(fd, "w") as fh:
    json.dump(cfg, fh, indent=2, sort_keys=True)
    fh.write("\\n")
os.replace(tmp, path)
print("wrote", path)
PYEOF

systemctl restart docker
echo "Done. Docker builder cache capped at %(keep_gb)dGB; container logs capped at %(log_max_file)dx%(log_max_size_mb)dMB."
'''


def daemon_json_script(keep_storage_gb=20, log_max_size_mb=100, log_max_file=3):
    """Render the display-only sudo script (validated ints only, never executed)."""
    return _DAEMON_SCRIPT_TEMPLATE % {
        'keep_gb': _int_in_range(keep_storage_gb, 'keep_storage_gb', 1, 10000),
        'log_max_size_mb': _int_in_range(log_max_size_mb, 'log_max_size_mb', 1, 10000),
        'log_max_file': _int_in_range(log_max_file, 'log_max_file', 1, 100),
    }
