"""Advanced Actions (red) unlock routes + secret/token helpers.

# ─────────────────────────────────────────────────────────────────────────
# Advanced-action gate
#
# The public webapp has no auth, so "read-only unless you hold the password"
# must be enforced server-side. An admin sets ONE `master_password` (PASSWORD
# param, admin-only plugin settings); the same value unlocks Advanced Actions
# in the browser, encrypts/decrypts remote-host API keys, and lets headless
# agents unlock red endpoints. A user unlocks by POSTing the plaintext to
# /api/auth/red/unlock; we compare and hand back a stateless signed token
# (key strengthened from the master password, so it auto-invalidates on
# rotation and validates across gunicorn workers with no shared state).
# Endpoints marked @advanced 403 without a valid token.
#
# Legacy (pre-0.4.659) installs stored a PBKDF2 hash in `red_actions_secret`
# (pbkdf2_sha256$<iters>$<b64salt>$<b64derived>, generated by the retired
# hash.html) plus plaintext copies in `red_actions_password` /
# `host_keys_password` for the agents. _red_secret_source() resolves the new
# field first, falls back to the legacy ones, and opportunistically migrates
# a legacy plaintext into `master_password` so the values survive DSS's
# prune-undeclared-keys-on-save behavior.
# ─────────────────────────────────────────────────────────────────────────

The `advanced` view decorator and the `_check_red_unlock` before_request gate
stay app-wide in backend.py; they import `_verify_red_token` and
`_RED_COOKIE_NAME` from here.
"""

import base64
import hashlib
import hmac
import json
import threading
import time

import dataiku
from flask import Blueprint, jsonify, request

from adk_backend import hostkeys
from adk_backend.utils import local_only

bp = Blueprint('auth', __name__)

_RED_TOKEN_TTL_SECONDS = 5 * 365 * 24 * 3600  # 5 years — effectively "remember forever"
_RED_SIGNING_CONTEXT = b'admin-toolkit-red-v1'
# The unlock token rides in an HttpOnly cookie (not JS-readable → XSS can't steal
# it; auto-sent with same-origin requests). SameSite=Lax keeps it off cross-site
# POST/DELETE, so the @advanced routes stay CSRF-safe.
_RED_COOKIE_NAME = 'admin_toolkit_red'


def _plugin_config() -> dict:
    """The `config` dict of LOCAL plugin settings (admin-only). PASSWORD params
    come back in plaintext through the admin API client (live-verified).

    Read from dataiku.api_client() (local) — the secret is anchored to the
    plugin install where the webapp runs, independent of the active host."""
    try:
        raw = dataiku.api_client().get_plugin('admin-toolkit').get_settings().get_raw()
        config = raw.get('config', {}) if isinstance(raw, dict) else {}
        return config if isinstance(config, dict) else {}
    except Exception:
        return {}


# One-shot guard for the lazy legacy→master_password settings migration.
_migrated_master_password = False


def _master_password() -> str:
    """The one master password (plaintext) from LOCAL plugin settings.

    Falls back to the legacy agents params (`red_actions_password` /
    `host_keys_password` — historically the same value) so a pre-0.4.659
    install keeps working untouched, and persists the fallback into
    `master_password` once so it survives DSS pruning undeclared config keys
    on the next settings save."""
    config = _plugin_config()
    master = (config.get('master_password') or '').strip()
    if master:
        return master
    legacy = (config.get('red_actions_password') or '').strip() \
        or (config.get('host_keys_password') or '').strip()
    if legacy:
        _migrate_master_password(legacy)
    return legacy


def _migrate_master_password(value: str) -> None:
    """Best-effort, once per process: copy a legacy plaintext into the new
    `master_password` setting (same save path the Remote Hosts preset CRUD
    already uses)."""
    global _migrated_master_password
    if _migrated_master_password:
        return
    _migrated_master_password = True
    try:
        settings = dataiku.api_client().get_plugin('admin-toolkit').get_settings()
        raw = settings.get_raw()
        config = raw.setdefault('config', {})
        if not (config.get('master_password') or '').strip():
            config['master_password'] = value
            settings.save()
    except Exception:
        pass


def _red_secret_source():
    """('plain', master_password) | ('hash', legacy_pbkdf2_string) | (None, '').

    The plaintext master password wins; a legacy `red_actions_secret` PBKDF2
    hash (from the retired hash.html flow) still verifies so hash-only
    upgrades stay unlocked. (None, '') = nothing configured, permanently
    locked."""
    master = _master_password()
    if master:
        return 'plain', master
    legacy_hash = (_plugin_config().get('red_actions_secret') or '').strip()
    if legacy_hash:
        return 'hash', legacy_hash
    return None, ''


def _verify_red_password(password: str, kind: str, stored: str) -> bool:
    """Verify a plaintext attempt against the secret source."""
    if kind == 'plain':
        return hmac.compare_digest(password.encode('utf-8'), stored.encode('utf-8'))
    # legacy: pbkdf2_sha256$iters$b64salt$b64derived
    try:
        algo, iters_s, salt_b64, hash_b64 = stored.split('$')
        if algo != 'pbkdf2_sha256':
            return False
        iters = int(iters_s)
        salt = base64.b64decode(salt_b64)
        expected = base64.b64decode(hash_b64)
        derived = hashlib.pbkdf2_hmac('sha256', password.encode('utf-8'), salt, iters, dklen=len(expected))
        return hmac.compare_digest(derived, expected)
    except Exception:
        return False


# Cache the PBKDF2-strengthened signing key: the gate verifies the token on
# every @advanced request, and 600k iterations per request would be brutal.
_signing_key_cache = {}
_signing_key_lock = threading.Lock()


def _red_signing_key(kind: str, stored: str) -> bytes:
    """Token-signing key. For a plaintext master password, strengthen through
    PBKDF2 first — a bare sha256(password) would let anyone holding a signed
    token brute-force the password offline. Legacy hash strings are already
    KDF output, so the historical sha256 derivation stays (and keeps existing
    unlock cookies valid across the upgrade)."""
    if kind != 'plain':
        return hashlib.sha256(stored.encode('utf-8') + _RED_SIGNING_CONTEXT).digest()
    with _signing_key_lock:
        key = _signing_key_cache.get(stored)
    if key is None:
        key = hashlib.pbkdf2_hmac('sha256', stored.encode('utf-8'),
                                  _RED_SIGNING_CONTEXT, 600000)
        with _signing_key_lock:
            _signing_key_cache.clear()  # one live password at a time
            _signing_key_cache[stored] = key
    return key


def _b64url(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).decode('ascii').rstrip('=')


def _b64url_decode(text: str) -> bytes:
    return base64.urlsafe_b64decode(text + ('=' * (-len(text) % 4)))


def _make_red_token(kind: str, stored: str, exp: int) -> str:
    payload = json.dumps({'exp': exp}, separators=(',', ':')).encode('utf-8')
    sig = hmac.new(_red_signing_key(kind, stored), payload, hashlib.sha256).digest()
    return _b64url(payload) + '.' + _b64url(sig)


def _red_token_exp_ms(token: str) -> int:
    """Epoch-ms expiry of a valid unlock token, or 0 if missing/forged/expired.
    Single source of truth for both the gate and /api/auth/red/status."""
    if not token or '.' not in token:
        return 0
    kind, stored = _red_secret_source()
    if not stored:
        return 0  # no password configured → permanently locked
    try:
        payload_b64, sig_b64 = token.split('.', 1)
        payload = _b64url_decode(payload_b64)
        expected_sig = hmac.new(_red_signing_key(kind, stored), payload, hashlib.sha256).digest()
        if not hmac.compare_digest(_b64url_decode(sig_b64), expected_sig):
            return 0
        exp = int(json.loads(payload.decode('utf-8')).get('exp', 0))
        return exp * 1000 if exp > int(time.time()) else 0
    except Exception:
        return 0


def _verify_red_token(token: str) -> bool:
    return _red_token_exp_ms(token) > 0


def _red_secure_cookie() -> bool:
    """Set the Secure flag when the browser↔edge hop is HTTPS. TLS terminates at
    the load balancer on the deployed hosts, so trust X-Forwarded-Proto."""
    return request.headers.get('X-Forwarded-Proto', '').lower() == 'https' or request.is_secure


def set_hostkey_cookie(resp, fernet_key: bytes) -> None:
    """Attach the HttpOnly host-key cookie carrying the derived Fernet key.

    Shared by the unlock endpoint and the preset writer's path-A auto-unlock, so
    a successful master-password encrypt also opens host-key decryption for the
    rest of the session (matching the unlock flow exactly)."""
    resp.set_cookie(
        hostkeys.KEY_COOKIE_NAME, fernet_key.decode('ascii'),
        max_age=_RED_TOKEN_TTL_SECONDS, path='/',
        secure=_red_secure_cookie(), httponly=True, samesite='Lax',
    )


@bp.route('/api/auth/red/unlock', methods=['POST'])
@local_only
def api_auth_red_unlock():
    """Verify a plaintext password against the master password; return a signed token."""
    kind, stored = _red_secret_source()
    if not stored:
        return jsonify({
            'error': 'not-configured',
            'message': 'No master password is configured. An administrator must set one in the plugin settings.',
        }), 400
    body = request.get_json(silent=True) or {}
    password = body.get('password') or ''
    if not _verify_red_password(password, kind, stored):
        return jsonify({'error': 'invalid-password', 'message': 'Incorrect password.'}), 401
    exp = int(time.time()) + _RED_TOKEN_TTL_SECONDS
    resp = jsonify({'unlocked': True, 'expiresAt': exp * 1000})
    resp.set_cookie(
        _RED_COOKIE_NAME, _make_red_token(kind, stored, exp),
        max_age=_RED_TOKEN_TTL_SECONDS, path='/',
        secure=_red_secure_cookie(), httponly=True, samesite='Lax',
    )
    # Same password opens the host-key gate — attach that cookie too so one
    # unlock covers everything (best-effort; blobs made under a different
    # password just stay locked until re-saved).
    blobs = _encrypted_host_blobs()
    if blobs:
        try:
            fernet_key = hostkeys.derive_fernet_key(password, hostkeys.salt_from_blob(blobs[0][1]))
            hostkeys.decrypt_blob(blobs[0][1], fernet_key)
            hostkeys.set_active_key(fernet_key)
            set_hostkey_cookie(resp, fernet_key)
        except Exception:
            pass
    return resp


@bp.route('/api/auth/red/status', methods=['GET'])
@local_only
def api_auth_red_status():
    """Report whether this browser holds a valid unlock cookie (UI hydration on
    boot). The token is HttpOnly, so JS can't read it — it asks the server."""
    exp_ms = _red_token_exp_ms(request.cookies.get(_RED_COOKIE_NAME, ''))
    return jsonify({'unlocked': exp_ms > 0, 'expiresAt': exp_ms})


@bp.route('/api/auth/red/lock', methods=['POST'])
@local_only
def api_auth_red_lock():
    """Forget the unlock on this device by clearing the cookie."""
    resp = jsonify({'unlocked': False})
    resp.delete_cookie(_RED_COOKIE_NAME, path='/')
    return resp


# ─────────────────────────────────────────────────────────────────────────
# Remote-host API-key unlock
#
# Remote-host preset API keys are stored encrypted as `adkfk1$` blobs
# (encrypted server-side with the master password when a host is saved).
# Since the master password lives in plugin settings, the backend derives the
# Fernet key itself on demand (auto_unlock_host_keys) — no user action needed.
# The browser unlock endpoint remains for legacy installs where only the old
# PBKDF2 hash is configured (no plaintext available server-side): the admin
# POSTs the password once and the derived key rides an HttpOnly cookie.
# ─────────────────────────────────────────────────────────────────────────


def auto_unlock_host_keys(blob: str):
    """Derive the host-key Fernet key from the stored master password, verify
    it opens `blob`, cache it process-wide, and return it — or None when no
    master password is configured / it doesn't decrypt this blob. Called from
    the preset resolver so encrypted keys open with zero user action."""
    password = _master_password()
    if not password:
        return None
    try:
        fernet_key = hostkeys.derive_fernet_key(password, hostkeys.salt_from_blob(blob))
        hostkeys.decrypt_blob(blob, fernet_key)
    except Exception:
        return None
    hostkeys.set_active_key(fernet_key)
    return fernet_key


def _encrypted_host_blobs():
    """[(host_id, blob)] for every remote-dss-host preset whose apiKey is an
    adkfk1$ encrypted blob. Read from LOCAL plugin settings (admin-only)."""
    try:
        raw = dataiku.api_client().get_plugin('admin-toolkit').get_settings().get_raw()
    except Exception:
        return []
    presets = raw.get('presets') if isinstance(raw, dict) else None
    if not isinstance(presets, list):
        return []
    out = []
    for preset in presets:
        if not isinstance(preset, dict):
            continue
        if not (preset.get('type') or '').endswith('remote-dss-host'):
            continue
        cfg = preset.get('config') or {}
        key = cfg.get('apiKey') or ''
        if hostkeys.is_encrypted(key):
            out.append((preset.get('name'), key))
    return out


@bp.route('/api/hosts/keys/unlock', methods=['POST'])
@local_only
def api_hosts_keys_unlock():
    """Verify the password decrypts the stored blobs, cache the derived key, and
    hand back an HttpOnly cookie carrying it. Reports any presets it couldn't
    decrypt (e.g. a blob made with a different salt)."""
    blobs = _encrypted_host_blobs()
    if not blobs:
        return jsonify({
            'error': 'not-configured',
            'message': 'No remote host has an encrypted API key. Encrypt a key with the tool and paste the adkfk1$… blob into the preset first.',
        }), 400
    body = request.get_json(silent=True) or {}
    password = body.get('password') or ''
    # All blobs share one salt; derive from the first and verify against it.
    salt = hostkeys.salt_from_blob(blobs[0][1])
    fernet_key = hostkeys.derive_fernet_key(password, salt)
    try:
        hostkeys.decrypt_blob(blobs[0][1], fernet_key)
    except Exception:
        return jsonify({'error': 'invalid-password', 'message': 'Incorrect password.'}), 401
    failed = []
    for host_id, blob in blobs:
        try:
            hostkeys.decrypt_blob(blob, fernet_key)
        except Exception:
            failed.append(host_id)
    exp = int(time.time()) + _RED_TOKEN_TTL_SECONDS
    hostkeys.set_active_key(fernet_key)
    resp = jsonify({'unlocked': True, 'expiresAt': exp * 1000, 'failed': failed})
    set_hostkey_cookie(resp, fernet_key)
    return resp


@bp.route('/api/hosts/keys/status', methods=['GET'])
@local_only
def api_hosts_keys_status():
    """Boot-time UI hydration: are any presets encrypted, and can they be
    opened (by this browser's cookie, or server-side via the master password)?"""
    blobs = _encrypted_host_blobs()
    configured = len(blobs) > 0
    unlocked = False
    cookie = request.cookies.get(hostkeys.KEY_COOKIE_NAME, '')
    if configured and cookie:
        try:
            hostkeys.decrypt_blob(blobs[0][1], cookie.encode('ascii'))
            unlocked = True
        except Exception:
            unlocked = False
    if configured and not unlocked:
        unlocked = auto_unlock_host_keys(blobs[0][1]) is not None
    return jsonify({'configured': configured, 'unlocked': unlocked})


@bp.route('/api/hosts/keys/lock', methods=['POST'])
@local_only
def api_hosts_keys_lock():
    """Forget the unlock on this device: clear the cookie and the process cache."""
    hostkeys.clear_active_key()
    resp = jsonify({'unlocked': False})
    resp.delete_cookie(hostkeys.KEY_COOKIE_NAME, path='/')
    return resp
