"""Advanced Actions (red) unlock routes + secret/token helpers.

# ─────────────────────────────────────────────────────────────────────────
# Advanced-action gate
#
# The public webapp has no auth, so "read-only unless you hold the password"
# must be enforced server-side. An admin stores a secret (a salted PBKDF2 hash)
# in the (admin-only) plugin setting `red_actions_secret` — generated by
# hash.html, which uses the SAME params as the verifier below. A user unlocks
# by POSTing the plaintext to /api/auth/red/unlock; we hash + compare and hand
# back a stateless signed token (key derived from the stored secret, so it
# auto-invalidates on password rotation and validates across gunicorn workers
# with no shared state). Endpoints marked @advanced 403 without a valid
# token. Phrase parsed/emitted in lockstep: pbkdf2_sha256$<iters>$<b64salt>$<b64derived>.
# ─────────────────────────────────────────────────────────────────────────

The `advanced` view decorator and the `_check_red_unlock` before_request gate
stay app-wide in backend.py; they import `_verify_red_token` and
`_RED_COOKIE_NAME` from here.
"""

import base64
import hashlib
import hmac
import json
import time

import dataiku
from flask import Blueprint, jsonify, request

from adk_backend.utils import local_only

bp = Blueprint('auth', __name__)

_RED_TOKEN_TTL_SECONDS = 5 * 365 * 24 * 3600  # 5 years — effectively "remember forever"
_RED_SIGNING_CONTEXT = b'admin-toolkit-red-v1'
# The unlock token rides in an HttpOnly cookie (not JS-readable → XSS can't steal
# it; auto-sent with same-origin requests). SameSite=Lax keeps it off cross-site
# POST/DELETE, so the @advanced routes stay CSRF-safe.
_RED_COOKIE_NAME = 'admin_toolkit_red'


def _red_secret() -> str:
    """The stored secret (PBKDF2 hash) from LOCAL plugin settings (admin-only).

    Read from dataiku.api_client() (local) — the secret is anchored to the
    plugin install where the webapp runs, independent of the active host.
    Empty string means no secret is configured (permanently locked)."""
    try:
        raw = dataiku.api_client().get_plugin('admin-toolkit').get_settings().get_raw()
        config = raw.get('config', {}) if isinstance(raw, dict) else {}
        return (config.get('red_actions_secret') or '').strip()
    except Exception:
        return ''


def _verify_red_password(password: str, stored: str) -> bool:
    """Verify plaintext against a pbkdf2_sha256$iters$b64salt$b64derived string."""
    try:
        algo, iters_s, salt_b64, hash_b64 = stored.split('$')
        if algo != 'pbkdf2_sha256':
            return False
        iters = int(iters_s)
        salt = base64.b64decode(salt_b64)
        expected = base64.b64decode(hash_b64)
        derived = hashlib.pbkdf2_hmac('sha256', password.encode('utf-8'), salt, iters, dklen=len(expected))
        return hmac.compare_digest(derived, expected)
    except Exception:
        return False


def _red_signing_key(stored: str) -> bytes:
    return hashlib.sha256(stored.encode('utf-8') + _RED_SIGNING_CONTEXT).digest()


def _b64url(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).decode('ascii').rstrip('=')


def _b64url_decode(text: str) -> bytes:
    return base64.urlsafe_b64decode(text + ('=' * (-len(text) % 4)))


def _make_red_token(stored: str, exp: int) -> str:
    payload = json.dumps({'exp': exp}, separators=(',', ':')).encode('utf-8')
    sig = hmac.new(_red_signing_key(stored), payload, hashlib.sha256).digest()
    return _b64url(payload) + '.' + _b64url(sig)


def _red_token_exp_ms(token: str) -> int:
    """Epoch-ms expiry of a valid unlock token, or 0 if missing/forged/expired.
    Single source of truth for both the gate and /api/auth/red/status."""
    if not token or '.' not in token:
        return 0
    stored = _red_secret()
    if not stored:
        return 0  # no password configured → permanently locked
    try:
        payload_b64, sig_b64 = token.split('.', 1)
        payload = _b64url_decode(payload_b64)
        expected_sig = hmac.new(_red_signing_key(stored), payload, hashlib.sha256).digest()
        if not hmac.compare_digest(_b64url_decode(sig_b64), expected_sig):
            return 0
        exp = int(json.loads(payload.decode('utf-8')).get('exp', 0))
        return exp * 1000 if exp > int(time.time()) else 0
    except Exception:
        return 0


def _verify_red_token(token: str) -> bool:
    return _red_token_exp_ms(token) > 0


def _red_secure_cookie() -> bool:
    """Set the Secure flag when the browser↔edge hop is HTTPS. TLS terminates at
    the load balancer on the deployed hosts, so trust X-Forwarded-Proto."""
    return request.headers.get('X-Forwarded-Proto', '').lower() == 'https' or request.is_secure


@bp.route('/api/auth/red/unlock', methods=['POST'])
@local_only
def api_auth_red_unlock():
    """Verify a plaintext password against the stored secret; return a signed token."""
    stored = _red_secret()
    if not stored:
        return jsonify({
            'error': 'not-configured',
            'message': 'No Advanced Actions secret is configured. An administrator must paste a secret into the plugin settings.',
        }), 400
    body = request.get_json(silent=True) or {}
    password = body.get('password') or ''
    if not _verify_red_password(password, stored):
        return jsonify({'error': 'invalid-password', 'message': 'Incorrect password.'}), 401
    exp = int(time.time()) + _RED_TOKEN_TTL_SECONDS
    resp = jsonify({'unlocked': True, 'expiresAt': exp * 1000})
    resp.set_cookie(
        _RED_COOKIE_NAME, _make_red_token(stored, exp),
        max_age=_RED_TOKEN_TTL_SECONDS, path='/',
        secure=_red_secure_cookie(), httponly=True, samesite='Lax',
    )
    return resp


@bp.route('/api/auth/red/status', methods=['GET'])
@local_only
def api_auth_red_status():
    """Report whether this browser holds a valid unlock cookie (UI hydration on
    boot). The token is HttpOnly, so JS can't read it — it asks the server."""
    exp_ms = _red_token_exp_ms(request.cookies.get(_RED_COOKIE_NAME, ''))
    return jsonify({'unlocked': exp_ms > 0, 'expiresAt': exp_ms})


@bp.route('/api/auth/red/lock', methods=['POST'])
@local_only
def api_auth_red_lock():
    """Forget the unlock on this device by clearing the cookie."""
    resp = jsonify({'unlocked': False})
    resp.delete_cookie(_RED_COOKIE_NAME, path='/')
    return resp
